# Video in Pytjon OpneCV

## Vedio Load

In [1]:
import cv2

class videos():
    
    def __init__(self, string):
        self.video = cv2.VideoCapture( string )
        self.name = string
        self.fps = self.video.get(cv2.CAP_PROP_FPS)
        self.f_count = self.video.get(cv2.CAP_PROP_FRAME_COUNT)
        self.f_width = self.video.get(cv2.CAP_PROP_FRAME_WIDTH)
        self.f_height = self.video.get(cv2.CAP_PROP_FRAME_HEIGHT)
        self.sec = self.f_count / self.fps
        self.nowrate = self.f_count / self.fps

    def __del__(self):
        self.video.release()
        
    def ShowPropeties(self):
        print(self.name + ' 정보')
        print('  fps:', self.fps)
        print('  f_count:', self.f_count)
        print('  f_width:', self.f_width)
        print('  f_height:', self.f_height)
        print('  Video_Length:', self.sec)
    

    def Close(self):
        self.video.release()
        

In [3]:
video1 = videos('영상1.mp4')
video2 = videos('영상2.mp4')
video3 = videos('영상3.mp4')

video1.ShowPropeties()

print(video1.name ," sec = ", video1.f_count / video1.fps)
print(video2.name ," sec = ", video2.sec)
print(video3.name ," sec = ", video3.sec)

video1.Close()
video2.Close()
video3.Close()

del video1
del video2
del video3

영상1.mp4 정보
  fps: 29.877551020408163
  f_count: 244.0
  f_width: 1920.0
  f_height: 1080.0
  Video_Length: 8.166666666666666
영상1.mp4  sec =  8.166666666666666
영상2.mp4  sec =  77.36666666666666
영상3.mp4  sec =  8.7


## Time

In [4]:
import time
start = time.time()  # 시작 시간 저장

print(time.time()-start)

cv2.waitKey(100)

print(time.time()-start)


0.0
0.12092900276184082


## Play Video

In [34]:
video1 = videos('영상1.mp4')

start = time.time()

while video1.video.isOpened():
    # 현재 재생시각을 받아와서, 재생시각의 Vedio Frame의 위치를 계산해서 지정
    nowsec = time.time()-start
    VideoSec = video1.f_count / video1.fps
    VideoRate = nowsec / VideoSec
    VideoNowFrame = VideoRate * video1.f_count
    video1.video.set(cv2.CAP_PROP_POS_FRAMES, VideoNowFrame)
    
    ret, frame = video1.video.read()

    print("Position = ", video1.video.get(cv2.CAP_PROP_POS_FRAMES))

    if ret :
        re_frame = cv2.resize(frame, (round(video1.f_width/4),round(video1.f_height/4)) )
        cv2.imshow('VideoView', re_frame)
        key = cv2.waitKey(int(1000/video1.fps))

        if key == ord('q'):
            break
    else:
        break

video1.video.set(cv2.CAP_PROP_POS_FRAMES, 0)

video1.Close()
cv2.destroyAllWindows()

Position =  1.0
Position =  5.0
Position =  8.0
Position =  11.0
Position =  14.0
Position =  17.0
Position =  20.0
Position =  23.0
Position =  26.0
Position =  29.0
Position =  32.0
Position =  35.0
Position =  38.0
Position =  41.0
Position =  45.0
Position =  48.0
Position =  62.0
Position =  66.0
Position =  69.0
Position =  74.0
Position =  78.0
Position =  83.0
Position =  87.0
Position =  92.0
Position =  97.0
Position =  101.0
Position =  106.0
Position =  111.0
Position =  114.0
Position =  117.0
Position =  121.0
Position =  123.0
Position =  127.0
Position =  129.0
Position =  133.0
Position =  135.0
Position =  138.0
Position =  141.0
Position =  144.0
Position =  147.0
Position =  150.0
Position =  154.0
Position =  157.0
Position =  160.0
Position =  163.0
Position =  167.0
Position =  171.0
Position =  175.0
Position =  178.0
Position =  182.0
Position =  186.0
Position =  190.0
Position =  195.0
Position =  200.0
Position =  202.0
Position =  204.0
Position =  206.0
Po

In [45]:
video1 = videos('영상1.mp4')

start = time.time()

while video1.video.isOpened():
    nowsec = time.time()-start
    video1.video.set(cv2.CAP_PROP_POS_FRAMES, nowsec * video1.fps)
    
    ret, frame = video1.video.read()

    if ret :
        re_frame = cv2.resize(frame, (round(video1.f_width/4),round(video1.f_height/4)) )
        cv2.imshow('VideoView', re_frame)
        key = cv2.waitKey(10)

        if key == ord('q'):
            break
    else:
        break

video1.video.set(cv2.CAP_PROP_POS_FRAMES, 0)

video1.Close()
cv2.destroyAllWindows()

### Play Vedio, Stop and Play

In [5]:
import cv2
import time

class videos():
    
    def __init__(self, string):
        self.video = cv2.VideoCapture( string )
        self.name = string
        self.fps = self.video.get(cv2.CAP_PROP_FPS)
        self.f_count = self.video.get(cv2.CAP_PROP_FRAME_COUNT)
        self.f_width = self.video.get(cv2.CAP_PROP_FRAME_WIDTH)
        self.f_height = self.video.get(cv2.CAP_PROP_FRAME_HEIGHT)
        self.sec = self.f_count / self.fps
        self.nowrate = self.f_count / self.fps

    def __del__(self):
        self.video.release()
        
    def ShowPropeties(self):
        print(self.name + ' 정보')
        print('  fps:', self.fps)
        print('  f_count:', self.f_count)
        print('  f_width:', self.f_width)
        print('  f_height:', self.f_height)
        print('  Video_Length:', self.sec)
    

    def Close(self):
        self.video.release()
    
    def Play(self, n = 0, string = 'VideoView'):
        StartFrame = n * self.fps
        self.video.set(cv2.CAP_PROP_POS_FRAMES, StartFrame)
        del StartFrame
        start = n + time.time()

        while self.video.isOpened():
            nowsec = n + time.time()-start
            self.video.set(cv2.CAP_PROP_POS_FRAMES, nowsec * self.fps)
            del nowsec

            ret, frame = self.video.read()

            if ret :
                re_frame = cv2.resize(frame, (round(self.f_width/2),round(self.f_height/2)) )
                del frame
                cv2.imshow(string, re_frame)
                key = cv2.waitKey(10)

                if key == ord('q'):
                    break

                if key == ord('s'):
                    print("Press s")
                    StopTime =  n + time.time()-start

                    keys = cv2.waitKey(0)
                    while(keys != ord('p')):
                        keys == cv2.waitKey(0)

                    print("Press p")
                    PlayTime =  n + time.time()-start
                    start += PlayTime - StopTime
                    del StopTime
                    del PlayTime

            else :
                break
        self.video.set(cv2.CAP_PROP_POS_FRAMES, 0)
        cv2.destroyAllWindows()

In [6]:
video2 = videos('영상2.mp4')

video2.ShowPropeties()

video2.Play()

영상2.mp4 정보
  fps: 29.98707453683757
  f_count: 2320.0
  f_width: 1920.0
  f_height: 1080.0
  Video_Length: 77.36666666666666
Press s
Press p
Press s
Press p


In [ ]:

cv2.destroyAllWindows()

## Audio Play

In [2]:
# pip install ffpyplayer
from ffpyplayer.player import MediaPlayer

In [6]:
player = MediaPlayer("mpmp.mp4")
val = ''
print("Player Start")
while val != 'eof':
    frame, val = player.get_frame()
    if val != 'eof' and frame is not None:
        img, t = frame
        print(frame)
        # display img
del player
print("End Player")

Player Start
(<ffpyplayer.pic.Image object at 0x00000196B1A19A80>, 0.0)
(<ffpyplayer.pic.Image object at 0x00000196B1A32540>, 0.0)
(<ffpyplayer.pic.Image object at 0x00000196B390EE40>, 0.16666666666666666)
(<ffpyplayer.pic.Image object at 0x00000196B1A19A80>, 0.2)
(<ffpyplayer.pic.Image object at 0x00000196B1A32540>, 0.23333333333333334)
(<ffpyplayer.pic.Image object at 0x00000196B390EE40>, 0.26666666666666666)
(<ffpyplayer.pic.Image object at 0x00000196B1A19A80>, 0.3)
(<ffpyplayer.pic.Image object at 0x00000196B1A32540>, 0.3333333333333333)
(<ffpyplayer.pic.Image object at 0x00000196B390EE40>, 0.36666666666666664)
(<ffpyplayer.pic.Image object at 0x00000196B1A19A80>, 0.4)
(<ffpyplayer.pic.Image object at 0x00000196B1A32540>, 0.43333333333333335)
(<ffpyplayer.pic.Image object at 0x00000196B390EE40>, 0.4666666666666667)
(<ffpyplayer.pic.Image object at 0x00000196B1A19A80>, 0.5)
(<ffpyplayer.pic.Image object at 0x00000196B1A32540>, 0.5333333333333333)
(<ffpyplayer.pic.Image object at 0x0

In [3]:
from ffpyplayer.player import MediaPlayer
import numpy as np
import cv2

player = MediaPlayer("영상1.mp4")
val = ''
print("Play Start")
while val != 'eof':
    frame, val = player.get_frame()
    if val != 'eof' and frame is not None:
        img, t = frame
        print(img)
        w = img.get_size()[0] 
        h = img.get_size()[1]
        arr = np.uint8(np.asarray(list(img.to_bytearray()[0])).reshape(h,w,3)) # h - height of frame, w - width of frame, 3 - number of channels in frame
        print(arr)
        arr=cv2.resize(arr,(320,520))
        cv2.imshow('test1111', arr)
        if cv2.waitKey(25) & 0xFF == ord('q'):
            cv2.destroyAllWindows()
            break
print("Play End")

Play Start
[[[ 29  29  29]
  [ 29  29  29]
  [ 29  29  29]
  ...
  [ 26  25  28]
  [ 26  25  28]
  [ 26  25  28]]

 [[ 29  29  29]
  [ 29  29  29]
  [ 29  29  29]
  ...
  [ 26  25  28]
  [ 26  25  28]
  [ 26  25  28]]

 [[ 27  27  27]
  [ 27  27  27]
  [ 29  29  29]
  ...
  [ 26  25  28]
  [ 26  25  28]
  [ 26  25  28]]

 ...

 [[209 217 224]
  [209 217 224]
  [209 217 224]
  ...
  [212 215 222]
  [212 215 222]
  [212 215 222]]

 [[212 215 222]
  [212 215 222]
  [212 215 222]
  ...
  [212 215 222]
  [212 215 222]
  [212 215 222]]

 [[212 215 222]
  [212 215 222]
  [212 215 222]
  ...
  [212 215 222]
  [212 215 222]
  [212 215 222]]]
[[[ 29  29  29]
  [ 29  29  29]
  [ 29  29  29]
  ...
  [ 26  25  28]
  [ 26  25  28]
  [ 26  25  28]]

 [[ 29  29  29]
  [ 29  29  29]
  [ 29  29  29]
  ...
  [ 26  25  28]
  [ 26  25  28]
  [ 26  25  28]]

 [[ 27  27  27]
  [ 27  27  27]
  [ 29  29  29]
  ...
  [ 26  25  28]
  [ 26  25  28]
  [ 26  25  28]]

 ...

 [[209 217 224]
  [209 217 224]
  [209 21

# Python-VLC

In [1]:
import vlc
import time

In [3]:
# vlc 미디어 플레이어 객체 생성하기
media_player = vlc.MediaPlayer()

# 재생할 뮤직비디오 파일을 vlc 모듈의 미디어로 변환.
media = vlc.Media("영상1.mp4")

# 읽어드린 미디어를 재생할 수 있도록 
# 미디어 플레이어 객체에 세팅 (재생 준비 상태)
media_player.set_media(media)

# start playing video
media_player.play()

# wait so the video can be played for 5 seconds
# irrespective for length of video
time.sleep(0.05)
  
# 비디오 정보 출력
print("Frame Rate per Second(fps) : ")
print(media_player.get_fps())
print("Video Width x Height : ")
print(str(media_player.video_get_width())
 + " x " +
 str(media_player.video_get_height()) )
print("Audio Volume : ")
print(media_player.audio_get_volume())
print("Video_Length : ")
print(media_player.get_length()/1000)

media_player.stop()
media_player.release()


Frame Rate per Second(fps) : 
29.87755012512207
Video Width x Height : 
1920 x 1080
Audio Volume : 
100
Video_Length : 
8.197


### Python-VLC 제어

In [20]:
media_player = vlc.MediaPlayer("--audio-visual=visual")
media = vlc.Media("영상2.mp4")
media_player.set_media(media)

# 영상 스케일 조정
media_player.video_set_scale(0.4)
time.sleep(1)
print(f"영상 스케일 : {media_player.video_get_scale}이다.")

# 볼륨 조정
media_player.audio_set_volume(80)
time.sleep(1)
print(f"영상 볼륨 : {media_player.audio_get_volume}이다.")

# 영상 1초 일지중지
media_player.pause()
time.sleep(1)

# 영상 1초 재생
media_player.play()
time.sleep(1)

# 영상 1초 중지
media_player.stop()
time.sleep(1)

# 영상 다시 재생
media_player.play()
time.sleep(1)

# 영상 위치 지정
media_player.set_position(0.3) # 30%
time.sleep(3)
print(f"  - 영상 재생시간: {media_player.get_time()}")
print(f"  - 영상 재생위치: {media_player.get_position()}")
print("\n")

# 영상 배속
media_player.set_rate(1.5) # 1.5배
time.sleep(3)
print(f"  - 현재 재생 속도: {media_player.get_rate()}")
print("\n")
media_player.set_rate(1) # 1배


# 음소거
media_player.audio_toggle_mute()
time.sleep(1)
value = media_player.audio_get_mute()
print(f"  - 현재 음소거 상태: {value}")
print("\n")
 
# 음소거 해제
media_player.audio_toggle_mute()
time.sleep(1)
value = media_player.audio_get_mute()
print(f"  - 현재 음소거 상태: {value}")
print("\n")
 
# 전체화면 - 영상비율도 같이 바꿔줘야 합니다.
media_player.video_set_scale(2)
media_player.set_fullscreen(True)
time.sleep(1)
print("  - 현재 Full screen 상태(get_fullscreen): ", media_player.get_fullscreen())
print("\n")
 
# 전체화면 해제 - 영상비율도 같이 바꿔줘야 합니다.
media_player.video_set_scale(0.4)
media_player.toggle_fullscreen()
time.sleep(1)
print("  - 현재 Full screen 상태(get_fullscreen): ", media_player.get_fullscreen())
print("\n")

# 영상 해제
media_player.release()


영상 스케일 : <bound method MediaPlayer.video_get_scale of <vlc.MediaPlayer object at 0x00000263F3DE2080>>이다.
영상 볼륨 : <bound method MediaPlayer.audio_get_volume of <vlc.MediaPlayer object at 0x00000263F3DE2080>>이다.
  - 영상 재생시간: 25686
  - 영상 재생위치: 0.33188918232917786


  - 현재 재생 속도: 1.5


  - 현재 음소거 상태: 1


  - 현재 음소거 상태: 0


  - 현재 Full screen 상태(get_fullscreen):  1


  - 현재 Full screen 상태(get_fullscreen):  0




### VLC Player 표준

In [6]:
# 영상 끝까지 재생 후 종료
media_player = vlc.MediaPlayer()


# Event
def my_call_back(event):
    print("콜백함수호출: 종료호출")
    global status 
    status = 1 
media_player.event_manager().event_attach(
    vlc.EventType.MediaPlayerStopped, my_call_back)

# Setting
media_player.set_media(vlc.Media("영상1.mp4"))
media_player.video_set_scale(0.2)
media_player.play()

# 자동 종료
status = 0
while True:
    time.sleep(0.3)
    if status == 1:
        media_player.release()
    else:
        pass
 

콜백함수호출: 종료호출


OSError: exception: access violation writing 0x0000000000000024

In [32]:
## instance를 활용한 표준

# 소리의 시각화
instance = vlc.Instance()
media_player = instance.media_player_new()

# 이벤트
def my_call_back(event):
    print("콜백함수호출: 종료호출")
    media_player.release()
media_player.event_manager().event_attach(
    vlc.EventType.MediaPlayerStopped, my_call_back)

# 영상 설정
media = instance.media_new("영상1.mp4")
media_player.set_media(media)
media_player.video_set_scale(0.2)
media_player.play()

## 자동 종료 안됨

0

콜백함수호출: 종료호출


### Python-VLC 소리의 시각화

In [11]:
# 소리의 시각화
instance = vlc.Instance(
    "--audio-visual=visual",
    "--effect-list=scope", #spectrum
    "--effect-fft-window=flattop")
media_player = instance.media_player_new()

# 이벤트
def my_call_back(event):
    print("콜백함수호출: 종료호출")
    media_player.release()
media_player.event_manager().event_attach(
    vlc.EventType.MediaPlayerStopped, my_call_back)

# 영상 설정
media_player.set_media(vlc.Media("영상1.mp4"))
media_player.video_set_scale(0.5)
media_player.play()

0

콜백함수호출: 종료호출


In [7]:
# 소리의 시각화
instance = vlc.Instance(
    "--audio-visual=visual",
    "--effect-list=scope",
    "--effect-fft-window=flattop")
media_player = instance.media_player_new()

# 이벤트
def my_call_back(event):
    print("콜백함수호출: 종료호출")
    media_player.release()
    global status 
    status = 1 
media_player.event_manager().event_attach(
    vlc.EventType.MediaPlayerStopped, my_call_back)

# 영상 설정
media_player.set_media(vlc.Media("영상1.mp4"))
media_player.video_set_scale(0.2)
media_player.play()

# 자동 종료
status = 0
while True:
    time.sleep(0.5)
    if status == 1:
        break
    else:
        print(media_player.audio_get_track_description())
        pass

[(-1, b'\xec\x82\xac\xec\x9a\xa9 \xec\x95\x88\xed\x95\xa8'), (1, b'\xed\x8a\xb8\xeb\x9e\x99 1')]
[(-1, b'\xec\x82\xac\xec\x9a\xa9 \xec\x95\x88\xed\x95\xa8'), (1, b'\xed\x8a\xb8\xeb\x9e\x99 1')]
[(-1, b'\xec\x82\xac\xec\x9a\xa9 \xec\x95\x88\xed\x95\xa8'), (1, b'\xed\x8a\xb8\xeb\x9e\x99 1')]
[(-1, b'\xec\x82\xac\xec\x9a\xa9 \xec\x95\x88\xed\x95\xa8'), (1, b'\xed\x8a\xb8\xeb\x9e\x99 1')]
[(-1, b'\xec\x82\xac\xec\x9a\xa9 \xec\x95\x88\xed\x95\xa8'), (1, b'\xed\x8a\xb8\xeb\x9e\x99 1')]
[(-1, b'\xec\x82\xac\xec\x9a\xa9 \xec\x95\x88\xed\x95\xa8'), (1, b'\xed\x8a\xb8\xeb\x9e\x99 1')]
[(-1, b'\xec\x82\xac\xec\x9a\xa9 \xec\x95\x88\xed\x95\xa8'), (1, b'\xed\x8a\xb8\xeb\x9e\x99 1')]
[(-1, b'\xec\x82\xac\xec\x9a\xa9 \xec\x95\x88\xed\x95\xa8'), (1, b'\xed\x8a\xb8\xeb\x9e\x99 1')]
[(-1, b'\xec\x82\xac\xec\x9a\xa9 \xec\x95\x88\xed\x95\xa8'), (1, b'\xed\x8a\xb8\xeb\x9e\x99 1')]
[(-1, b'\xec\x82\xac\xec\x9a\xa9 \xec\x95\x88\xed\x95\xa8'), (1, b'\xed\x8a\xb8\xeb\x9e\x99 1')]
[(-1, b'\xec\x82\xac\xec\x9a\x

KeyboardInterrupt: 